### GET request to example server
GET http://localhost:8001/user-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNU1mc0ZYN3BFZHNhVjdacUlOdEszQlEwU0ciLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDIiLCJleHAiOjE3NjMwMDE2MDMsImZ2YSI6WzAsLTFdLCJpYXQiOjE3NjMwMDE1NDMsImlzcyI6Imh0dHBzOi8vYWxsb3dlZC1mb3dsLTU1LmNsZXJrLmFjY291bnRzLmRldiIsImp0aSI6IjRjYWY2YTUxZDQyYTlkM2VmNGRmIiwibWV0YWRhdGEiOnsicm9sZSI6InVzZXIifSwibmJmIjoxNzYzMDAxNTMzLCJzaWQiOiJzZXNzXzM1UEFzYVhMcFY1bjkyY1B6REJoV2FuVEl3UCIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzVNZ05mZDhCODZ2Tkp2Wkxwd0JiOHNmOUJEIiwidiI6Mn0.VaNbaBSNS4PATZcvbSTFH5CPRagl44cl-Tbo9mqFD817WP89m6ShyMhhxA-RpO7uym_vu8uHNHDifD44zFJIYuebHFvNQ4Jm5rAwSdWP-_rn9k95JDSEW64VyHybLMrzViSq3IpuLwmA44H4NKon8iqdnRan72Urng6bdRGPSCMXk4uJa9G6t1qSdVLRpvB5B3aQh-gFILcBwyyh-R8XdyRpyCCMN8qgZN3r_qezXbV3hya4xjavO16ECXwO1wtPigXitjQpL07tjz7tvPMUn7JwplwFYuAcScaGV2_u6m_EKgTsfmc0B7RXOPu-0Y5JghvulgWRuob-uxvUFFcN-Q

### GET request to example server
GET http://localhost:8001/user-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNU1mc0ZYN3BFZHNhVjdacUlOdEszQlEwU0ciLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDIiLCJleHAiOjE3NjMwMDE2MDMsImZ2YSI6WzAsLTFdLCJpYXQiOjE3NjMwMDE1NDMsImlzcyI6Imh0dHBzOi8vYWxsb3dlZC1mb3dsLTU1LmNsZXJrLmFjY291bnRzLmRldiIsImp0aSI6IjRjYWY2YTUxZDQyYTlkM2VmNGRmIiwibWV0YWRhdGEiOnsicm9sZSI6InVzZXIifSwibmJmIjoxNzYzMDAxNTMzLCJzaWQiOiJzZXNzXzM1UEFzYVhMcFY1bjkyY1B6REJoV2FuVEl3UCIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzVNZ05mZDhCODZ2Tkp2Wkxwd0JiOHNmOUJEIiwidiI6Mn0.VaNbaBSNS4PATZcvbSTFH5CPRagl44cl-Tbo9mqFD817WP89m6ShyMhhxA-RpO7uym_vu8uHNHDifD44zFJIYuebHFvNQ4Jm5rAwSdWP-_rn9k95JDSEW64VyHybLMrzViSq3IpuLwmA44H4NKon8iqdnRan72Urng6bdRGPSCMXk4uJa9G6t1qSdVLRpvB5B3aQh-gFILcBwyyh-R8XdyRpyCCMN8qgZN3r_qezXbV3hya4xjavO16ECXwO1wtPigXitjQpL07tjz7tvPMUn7JwplwFYuAcScaGV2_u6m_EKgTsfmc0B7RXOPu-0Y5JghvulgWRuob-uxvUFFcN-Q